version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ott_user
      POSTGRES_PASSWORD: ott_password
      POSTGRES_DB: ott_db
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: